apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials:
    aws_access_key_id = ASIATV7EMFFZ64ILOJWF
    aws_secret_access_key = IrNs+1ovg7VH+rehZl37hxG5U2rmWPfaRgs/OMBi
    aws_secret_session_token = FwoGZXIvYXdzEC4aDNK3WGAFbhSd+VZy3yLVAXJgD/u7dwJnRKhl9/VNaQGosLsPQX37/JVqPGReOQ8587YM3H3wMZya45CkYk8giNqXZRA2E9iwjNYl0QVqB7VC46PFJ89Uxg5yYGTfqhLeZM04LyKqWD8Rp46dhAzhHem1TQmgeBzqnGNRidt849KkfHXpH8i8WJPXtuYzFCOdEtaM2Mq61rCiIDR9gHtMlUFAQI9x/FZwCniUnbSjdHTHCvYpsJjdPCsbpZc7+kuiRjIodvsysR/jfjtdA0z+JzGh+gCgvkP03wx4So8UzqeRYsWEfSi1z56bBjItjzlMOe9ZCZ7mnwOuKvFuv4Kgn4XAEmQvCnDpiv4PZkVe9ioxmSyhDuUOrFT6